# docker-compose.yml

services:
  frontend:
    image: trovares/desktop_frontend
    ports:
      - "${TD_PORT:-80}:80"
      - "${TD_SSL_PORT:-443}:443"
    networks:
      - external-network
    volumes:
      - ${TD_SSL_PUBLIC_CERT:-/dev/null}:/etc/ssl/certs/td.pem:ro
      - ${TD_SSL_PRIVATE_KEY:-/dev/null}:/etc/ssl/private/td.pem:ro

  backend:
    image: trovares/desktop_backend
    environment:
      TD_MONGO_URI: mongodb://mongodb:27017
      TD_DEFAULT_XGT_HOST:
      TD_DEFAULT_XGT_PORT:
      TD_SESSION_TTL:
      TD_SSL_PUBLIC_CERT:
      TD_SSL_PRIVATE_KEY:
      XGT_SERVER_CN:
      XGT_AUTH_TYPES:
    networks:
      - database-network
      - external-network
    volumes:
      - ${XGT_SSL_SERVER_CERT:-/dev/null}:/etc/ssl/certs/xgt-server.pem:ro
      - mongodb-data:/app/data
      # Uncomment and configure the line below to setup odbc.
      # - ./odbc:/odbc

  xgt:
    image: trovares/xgt
    ports:
      - "4367:4367"
    volumes:
      - ${XGT_DATA_PATH:-/tmp}:/data
    networks:
      - external-network

  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - database-network
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  database-network:
    internal: true
  external-network:
