# docker-compose.yml

services:
  frontend:
    image: trovares/desktop_frontend
    ports:
      - "${TD_PORT:-80}:80"
      - "${TD_SSL_PORT:-443}:443"
    networks:
      - external-network
    volumes:
      - ${TD_SSL_PUBLIC_CERT:-/dev/null}:/etc/ssl/certs/td.pem:ro
      - ${TD_SSL_PRIVATE_KEY:-/dev/null}:/etc/ssl/private/td.pem:ro

  backend:
    image: trovares/desktop_backend
    environment:
      TD_MONGO_URI: mongodb://mongodb:27017
      TD_ACCESS_TOKEN_EXPIRES:
      TD_DEFAULT_XGT_HOST:
      TD_DEFAULT_XGT_PORT:
      XGT_SERVER_CN:
    networks:
      - database-network
      - external-network
    volumes:
      - ${XGT_SSL_SERVER_CERT:-/dev/null}:/etc/ssl/certs/xgt-server.pem:ro
      - mongodb-data:/app/data
    # Uncomment these lines if using Docker Engine and running Trovares Desktop
    # on the same host as the xGT server.
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  xgt:
    image: trovares/xgt
    ports:
      - "4367:4367"
    volumes:
      - ${XGT_DATA_PATH:-/tmp}:/data
    networks:
      - external-network

  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - database-network
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  database-network:
    internal: true
  external-network:
